---
title: "Modelling"
author: "u1805379"
date: "17/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
```

```{r libraries, include=FALSE}
library(devtools)
library(zoo)
library(MASS)
source_url("https://raw.github.com/timleeman/ST344GroupProject/main/setup.R")
source_url("https://raw.github.com/timleeman/ST344GroupProject/main/getdata.R")
covidData$date = as.Date(parse_date_time(covidData$date,orders=c("y","ym","ymd")))
TidyData <- covidData %>% group_by(country) 
TidyData <- mutate(TidyData, country = factor(country), continent = factor(continent))

firstdiff <- function(x) {
  shifted <- c(0,x[1:(length(x)-1)])
  result = x-shifted
  which_negative = which(result<0)
  result[which_negative] = NA
  return(result) }

covidData <- covidData %>%
  mutate(daily_confirmed = firstdiff(confirmed))

```



```{r lockdown_length calculator,}
national_lockdowns <- auravisionData %>% filter(Level== "National") %>% dplyr::select(-Level)
national_lockdowns <- national_lockdowns %>% mutate(national_lockdown_length = as.numeric(-difftime(`StartDate`, `EndDate`)))
colnames(national_lockdowns)[1] = "country"
national_lockdowns <- filter(national_lockdowns, country %in% chosenCountries)
head(national_lockdowns %>% dplyr::select(country, national_lockdown_length) %>% arrange(national_lockdown_length),60)
```

```{r functions_to_get_lockdown_data_and_bind,}
selectData <- filter(covidData, country %in% chosenCountries)
#Function to select country
pre_lockdown_start_date <- function(cou){
  a <- national_lockdowns %>% filter(country == cou) %>% dplyr::select(`StartDate`)
  return(a$`StartDate`[1] - 7) 
}
lockdown_start_date <- function(cou){
  a <- national_lockdowns %>% filter(country == cou) %>% dplyr::select(`StartDate`)
  return(a$`StartDate`[1]) 
}
lockdown_end_date <- function(cou){
  a <- national_lockdowns %>% filter(country == cou) %>% dplyr::select(`EndDate`)
  return(a$`EndDate`[1]) 
}
get_lockdown_data <- function(cou){
  if(is.na(lockdown_end_date(cou))){
    lockdown_data <- selectData %>% filter(country == cou) %>% 
                    filter(date >= pre_lockdown_start_date(cou)) %>%
                    mutate(days_in_lockdown = as.numeric(-difftime(lockdown_start_date(cou), date)/86400),
                           rolling_gcmr_retail = zoo::rollmean(gcmr_retail_recreation, k = 7, fill = NA),
                           rolling_gcmr_grocery = zoo::rollmean(gcmr_grocery_pharmacy, k = 7, fill = NA),
                           peak_daily_cases = max(daily_confirmed, na.rm= T))
    return(lockdown_data)
  }
  lockdown_data <- selectData %>% filter(country == cou) %>% 
                    filter(date >= pre_lockdown_start_date(cou)) %>%
                    filter(date < lockdown_end_date(cou)) %>%
                    mutate(days_in_lockdown = as.numeric(-difftime(lockdown_start_date(cou), date)/86400),
                           rolling_gcmr_retail = zoo::rollmean(gcmr_retail_recreation, k = 7, fill = NA),
                           rolling_gcmr_grocery = zoo::rollmean(gcmr_grocery_pharmacy, k = 7, fill = NA),
                           peak_daily_cases = max(daily_confirmed, na.rm= T))
  return(lockdown_data)
}

get_peak_daily_cases_day <- function(cou){
  most_in_day <- get_lockdown_data(cou)$peak_daily_cases[1]
  most_day <- get_lockdown_data(cou) %>% filter(daily_confirmed == most_in_day)
  most_day_date <- most_day$date[1]
  return(most_day_date)
}

lockdown_data <- data_frame()
for(cou in national_lockdowns$country){
  a <- get_lockdown_data(cou)
  lockdown_data <- rbind(a, lockdown_data)
}


# get_peak_daily_cases_day("Germany")
# get_lockdown_data("Germany")
```

```{r calculating_the_r, message=FALSE, warning=FALSE}

#We calculated the R number for three periods in each country's epidemic 

#The first function uses the 28 days leading up to lockdown, it returns NA for countries that had a maximum of 10 daily cases during the period because the high R's calculated were not justifiable
before_lockdown_r <- function(cou){
  startday <- lockdown_start_date(cou) - 28
  endday <- lockdown_start_date(cou)
  key_data <- selectData %>% dplyr::select(country, date, daily_confirmed) %>%
    filter(date >= startday & date < endday) %>% filter(country == cou) %>% na.omit()
  if(max(key_data$daily_confirmed) < 10){
    return(NA)
  }
  daily_cases_model <- glm.nb(daily_confirmed ~ 1 + date, data = key_data)
  key_data$pred_daily_cases <- predict(daily_cases_model)
  R <-  exp(4*(coef(daily_cases_model)[2] %>% as.numeric))
  return(R)
}


#The second R uses the 28 days from the day with the most cases in lockdown
during_lockdown_r <- function(cou){
  startday <- get_peak_daily_cases_day(cou)
  endday <- startday + 28
  key_data <- selectData %>% dplyr::select(country, date, daily_confirmed) %>%
    filter(date >= startday & date < endday) %>% filter(country == cou) %>% na.omit()
  daily_cases_model <- glm.nb(daily_confirmed ~ 1 + date, data = key_data)
  key_data$pred_daily_cases <- predict(daily_cases_model)
  R <-  exp(4*(coef(daily_cases_model)[2] %>% as.numeric))
  return(R)
}


#This uses the 7 days after lockdown. Some countries were still in lockdown at the end of the dataset so if a lockdown end date was not found from Auravision, we use the during lockdown functions result for continuity.
post_lockdown_r <- function(cou){
  if(is.na(lockdown_end_date(cou))){
    return(during_lockdown_r(cou))
  }
  startday <- lockdown_end_date(cou)
  endday <- startday + 7
  key_data <- selectData %>% dplyr::select(country, date, daily_confirmed) %>%
    filter(date > startday & date <= endday) %>% filter(country == cou) %>% na.omit()
  daily_cases_model <- glm.nb(daily_confirmed ~ 1 + date, data = key_data)
  key_data$pred_daily_cases <- predict(daily_cases_model)
  R <-  exp(4*(coef(daily_cases_model)[2] %>% as.numeric))
  return(R)
}

lst <- list(country= c(), before_lockdown_r= c(), during_lockdown_r= c(), post_lockdown_r= c())

Rdata <- as.data.frame(lst)


#Calculates the three R values 
calculate_r <- function(x){
  a <- before_lockdown_r(x) 
  b <- during_lockdown_r(x)
  c <- post_lockdown_r(x)
  row <- data.frame(country = x,
                  before_lockdown_r = a, 
                  during_lockdown_r = b,
                  post_lockdown_r = c)
  return(row)
}

# Binding the R data for each country in national lockdown
for(i in national_lockdowns$country){
  Rdata <- rbind(Rdata, calculate_r(i))
}


```

```{r exploring_Rdata,}

head(Rdata,45)
ggplot(Rdata, aes(x= before_lockdown_r)) + geom_boxplot() + 
  labs(x= "R", title= "Distribution of R before Lockdown",
       subtitle= "R calculated from the 28 days before lockdown") 
ggplot(Rdata, aes(x= during_lockdown_r)) + geom_boxplot() + 
  labs(x= "R", title= "Distribution of R from peak cases day",
       subtitle= "R calculated from the 28 days after the peak cases day in lockdown") 
ggplot(Rdata, aes(x= post_lockdown_r)) + geom_boxplot() + 
  labs(x= "R", title= "Distribution of R after Lockdown",
       subtitle= "R calculated from the 7 days after lockdown") 

```



```{r model_data,}
average_temperature <- import("https://raw.github.com/timleeman/ST344GroupProject/main/Modelling/average_temperature_edit.xlsx")
modelData <- lockdown_data %>% dplyr::select(country, date, continent, gdp_capita, rolling_gcmr_retail, 
                                      rolling_gcmr_grocery, days_in_lockdown, income) %>%  distinct()
modelData <- left_join(modelData, average_temperature, by= "country")

modelData$gdp_capita <- scale(modelData$gdp_capita)
#modelData$average_temperature <- scale(modelData$average_temperature)
modelData <- modelData %>% na.omit() 
modelData <- modelData %>% mutate(days_squared = days_in_lockdown^2)
population_20_39 <- import("https://raw.github.com/timleeman/ST344GroupProject/main/Modelling/population_aged_20_39.xlsx")
population_20_39 <- dplyr::select(population_20_39, country, `2019`)
population_40_59 <- import("https://raw.github.com/timleeman/ST344GroupProject/main/Modelling/population_aged_40_59.xlsx")
population_40_59 <- dplyr::select(population_40_59, country, `2019`)
population_20_59 <- left_join(population_20_39, population_40_59, by= "country")
population_20_59 <- population_20_59 %>% transmute(country, pop_20_59= `2019.x` + `2019.y` )
modelData <- left_join(modelData, population_20_59, by= "country")
head(modelData,500)
```

```{r justification_for_first_model,}
plot_country_lockdown_gcmr_retail <- function(cou){
  a <- modelData %>% filter(country == cou)
  ggplot(a, aes(x= date, y= rolling_gcmr_retail)) + geom_line()
}
#plot_country_lockdown_gcmr_retail("Germany")
ggplot(modelData, aes(x=days_in_lockdown, y= rolling_gcmr_retail, group= country, col= average_temperature)) + geom_line()
ggplot(modelData, aes(x=days_in_lockdown, y= rolling_gcmr_retail, group= country, col= income)) + geom_line()
ggplot(modelData, aes(x=days_in_lockdown, y= rolling_gcmr_retail, group= country, col= pop_20_59)) + geom_line()
```


```{r first_model,}
model1 <- lm(data= modelData, rolling_gcmr_retail ~ days_in_lockdown)
summary(model1)
```

```{r grouping_by_lockdown_length, warning=FALSE}
modelData <- left_join(modelData, national_lockdowns, by = "country")
#gets rid of the Place column, it was causing probblems with stepwise regression and is basically useless here
modelData$Place <- NULL
#ggplot(average_lockdown_modelData, aes(x=days_in_lockdown, y= gcmr_retail_recreation, group= country, col= average_temperature)) + geom_line()
#model2 <- lm(data= average_lockdown_modelData, gcmr_retail_recreation ~ days_in_lockdown)
#summary(model2)
#A minimal and maximal model we want to consider, haven't yet considered interactions between variables
minModel <- glm(data = modelData, rolling_gcmr_retail ~ 1)
maxModel <- glm(data = modelData, rolling_gcmr_retail ~ gdp_capita + days_in_lockdown + 
                                                            average_temperature + 
                                                            national_lockdown_length + factor(lockdownCategory))
#stepwise regression backwards, forwards and both directions
autoBack <- step(maxModel, direction = "backward", scope = list("lower" = minModel))
autoForward <- step(minModel, direction = "forward", scope = list("upper" = maxModel))
autoBoth <- step(minModel, direction = "both", scope = list("lower" = minModel, "upper" = maxModel))
summary(autoBack)
summary(autoForward)
summary(autoBoth)
#Forward, backward and both directions stepwise regression all choose the same model which is encouraging
#Exhaustive search for best model
regsubsetsOut <- regsubsets(rolling_gcmr_retail ~ gdp_capita + days_in_lockdown + average_temperature + 
                               national_lockdown_length + factor(lockdownCategory), data = modelData)
plot(regsubsetsOut, scale = "Cp")
```